### ISSUE TITLE
Defekte Links in Cases.md

### ISSUE THREAD

**Issue by tgodau** [ifrOSS/ifrOSS#16]
Leider funktionieren folgende Links in Cases.md nicht:

```
LG Bochum, Teilurteil v. 10.02.2011, Az. I-8 O 293/09

adhoc dataservice GmbH ./. Buhl Data Service GmbH

Link: http://www.telemedicus.info/urteile/Urheberrecht/Open-Source/1148-LG-Bochum-Az-I-8-O-29309-Ansprueche-bei-Verletzung-der-LGPL.html
```
(WaybackMachine: https://web.archive.org/web/20200814141346/https://www.telemedicus.info/urteile/Urheberrecht/Open-Source/1148-LG-Bochum-Az-I-8-O-29309-Ansprueche-bei-Verletzung-der-LGPL.html)

und

```
BPatG, Beschluss v. 17.12.2009, Az. 25 W (pat) 65/08

„Linuxwerkstatt“ (§ 8 Abs. 2 Nr. 1 MarkenG)

Link: http://www.bundespatentgericht.de/bpatg/leitsaetze/marken/25065_08.pdf
```
(WaybackMachine: https://web.archive.org/web/20150924212639/https://www.bundespatentgericht.de/bpatg/leitsaetze/marken/25065_08.pdf)

Gruß, Thorsten

**Comment by LeChasseur** [comment]
Vielen Dank, ist aktualisiert.
