### ISSUE TITLE
Defekter Link in Lizenzcenter.md

### ISSUE THREAD

**Issue by tgodau** [ifrOSS/ifrOSS#17]
Lieder funktioniert der Link zur IPL-1.0 nicht:

`18. IBM Public License: http://oss.software.ibm.com:80/developerworks/opensource/license10.html`

Unter [https://www.ibm.com/opensource](https://www.ibm.com/opensource) konnte ich leider nichts zu diesem Lizenztext finden.

Die WaybackMachine liefert lediglich für den 05.03.2005 letztmalig einen brauchbaren Inhalt:
[https://web.archive.org/web/20050305085348/http://oss.software.ibm.com/developerworks/opensource/license10.html](https://web.archive.org/web/20050305085348/http://oss.software.ibm.com/developerworks/opensource/license10.html)

Gruß, Thorsten

**Comment by LeChasseur** [comment]
Vielen Dank für den Hinweis. Da die Lizenz nicht mehr genutzt wird, bleibt wohl nur die Wayback Machine. Werden wir aufnehmen.
